export { type Document, make } from "./document"
export { Property } from "./property"
export { type Part, makePart } from "./part"
export { type Car, makeCar } from "./car"
export { type HasType, hasType } from "./traits/hasType"
export { type HasModel, hasModel } from "./traits/hasModel"
export { type HasPrice, hasPrice } from "./traits/hasPrice"
export { type HasParts, hasParts } from "./traits/hasParts"
